### ISSUE TITLE
make xenial the default branch

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch-sdk-api-scripts#5]
is this repo still used for doc generation ?
If not can we make it archived ?

**Comment by bhdouglass** [comment]
It's not actively being used, but nothing has replaced it, nor has the uitk been updated much.

**Comment by lduboeuf** [comment]
yes was thinking of deprecated things such as Ubuntu.Components.ListsItems or Ubuntu.Web.

**Comment by bhdouglass** [comment]
Yeah that sounds like a good idea, the uitk docs need some love.

**Comment by lduboeuf** [comment]
humm, but of what i see, Morph.Web does not have updated doc. I will have a look at it

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/infrastructure/ubuntu-touch-sdk-api-scripts/-/issues/5
